name: infinum_architecture
description: A new Flutter project with Infinum clean architecture.
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  firebase_crashlytics: ^2.8.6
  flutter:
    sdk: flutter
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^4.2.0
  hooks_riverpod: ^1.0.4
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  loggy: ^2.0.1+1
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3

flutter:
  uses-material-design: true
