name: picmore
description: app to test performance.
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bitmap: ^0.1.2
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_hooks: ^0.18.5+1
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3
  flutter_svg: ^1.1.3
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^4.2.0
  hooks_riverpod: ^1.0.4
  image: ^3.2.0
  image_gallery_saver: ^1.7.1
  infinite_scroll_pagination: ^3.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  loggy: ^2.0.1+1
  ml_linalg: ^13.10.0
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
